version: "3.9"

services:

    server:
        container_name: server
        image: server
        restart: always
        build:
            context: ./app/
            dockerfile: Dockerfile
            target: base
        ports:
            - "80:3000" 
        volumes:
            - ./app/:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data:
    node_modules:
    web-root:
      driver: local
